//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSaucisseFactory
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TheSaucisseFactory.Batiment))]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Namespace="http://schemas.thesaucissefactory.com", ItemName="Batiment")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TheSaucisseFactory.Batiment))]
    public partial class BatimentCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<TheSaucisseFactory.Batiment>, System.Collections.Generic.ICollection<TheSaucisseFactory.Batiment>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<TheSaucisseFactory.Batiment> _baseList = new System.Collections.Generic.List<TheSaucisseFactory.Batiment>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.Batiment> _baseTable = new System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.Batiment>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private TheSaucisseFactory.Residence _batimentsResidenceResidence;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.Batiment> _blm3483504819;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public BatimentCollection()
        {
            this._blm3483504819 = new CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.Batiment>(this);
        }
        
        public BatimentCollection(TheSaucisseFactory.Residence batimentsResidenceResidence)
        {
            this._blm3483504819 = new CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.Batiment>(this);
            this._batimentsResidenceResidence = batimentsResidenceResidence;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<TheSaucisseFactory.Batiment> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.Batiment> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public TheSaucisseFactory.Residence BatimentsResidenceResidence
        {
            get
            {
                return this._batimentsResidenceResidence;
            }
        }
        
        public TheSaucisseFactory.Batiment this[int index]
        {
            get
            {
                return ((TheSaucisseFactory.Batiment)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((TheSaucisseFactory.Batiment)(value));
            }
        }
        
        public TheSaucisseFactory.Batiment this[System.Guid id]
        {
            get
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                TheSaucisseFactory.Batiment i = this.TryGetValue(id);
                return i;
            }
            set
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                if ((value == null))
                {
                    TheSaucisseFactory.Batiment batiment = this.TryGetValue(id);
                    if ((batiment != null))
                    {
                        this.Remove(batiment);
                    }
                    return;
                }
                TheSaucisseFactory.Batiment existing = this.TryGetValue(value.Id);
                if ((existing != null))
                {
                    this.Remove(existing);
                }
                this.Add(value);
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm3483504819.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm3483504819.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm3483504819.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm3483504819.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm3483504819.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm3483504819.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm3483504819.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm3483504819.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(TheSaucisseFactory.Batiment item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(TheSaucisseFactory.Batiment batiment)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(batiment);
            return localAdd;
        }
        
        protected virtual int BaseAdd(TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                throw new System.ArgumentNullException("batiment");
            }
            if ((batiment.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "batiment", "TheSaucisseFactory.Batiment");
            }
            try
            {
                this.BaseTable.Add(batiment.Id, batiment);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.BatimentCollection", batiment.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.BatimentCollection", batiment.Id), ae);
            }
            batiment.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            if ((this._batimentsResidenceResidence != null))
            {
                batiment.Residence = this._batimentsResidenceResidence;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(batiment);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, batiment, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            TheSaucisseFactory.Batiment batiment = null;
            try
            {
                batiment = ((TheSaucisseFactory.Batiment)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((batiment == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(batiment);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<TheSaucisseFactory.Batiment>.Add(TheSaucisseFactory.Batiment batiment)
        {
            this.BaseAdd(batiment);
        }
        
        public virtual TheSaucisseFactory.Batiment AddByEntityKey(string key)
        {
            TheSaucisseFactory.Batiment batiment = TheSaucisseFactory.Batiment.LoadByEntityKey(key);
            if (((batiment != null) 
                        && (this.Contains(batiment) == false)))
            {
                this.Add(batiment);
            }
            return batiment;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<TheSaucisseFactory.Batiment> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(TheSaucisseFactory.Batiment[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(TheSaucisseFactory.Batiment[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(TheSaucisseFactory.Batiment batiment)
        {
            bool localContains = this.BaseContains(batiment);
            return localContains;
        }
        
        protected virtual bool BaseContains(TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(batiment.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            TheSaucisseFactory.Batiment batiment;
			batiment = value as TheSaucisseFactory.Batiment;
            return this.Contains(batiment);
        }
        
        public int IndexOf(TheSaucisseFactory.Batiment batiment)
        {
            int localIndexOf = this.BaseIndexOf(batiment);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(batiment);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            TheSaucisseFactory.Batiment batiment;
			batiment = value as TheSaucisseFactory.Batiment;
            return this.IndexOf(batiment);
        }
        
        public void Insert(int index, TheSaucisseFactory.Batiment batiment)
        {
            this.BaseInsert(index, batiment);
        }
        
        protected virtual void BaseInsert(int index, TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                throw new System.ArgumentNullException("batiment");
            }
            try
            {
                this.BaseTable.Add(batiment.Id, batiment);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.BatimentCollection", batiment.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.BatimentCollection", batiment.Id), ae);
            }
            this.BaseList.Insert(index, batiment);
            if ((this._batimentsResidenceResidence != null))
            {
                batiment.Residence = this._batimentsResidenceResidence;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, batiment, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            TheSaucisseFactory.Batiment batiment;
			batiment = value as TheSaucisseFactory.Batiment;
            this.Insert(index, batiment);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                TheSaucisseFactory.Batiment Batiment = this[0];
                this.BaseRemove(Batiment);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(TheSaucisseFactory.Batiment batiment)
        {
            return this.BaseRemove(batiment);
        }
        
        protected virtual bool BaseRemove(TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                throw new System.ArgumentNullException("batiment");
            }
            int index = this.IndexOf(batiment);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<TheSaucisseFactory.Batiment>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(batiment);
            batiment.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(batiment.Id);
            if ((this._batimentsResidenceResidence != null))
            {
                batiment.Residence = null;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, batiment, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            TheSaucisseFactory.Batiment batiment;
			batiment = value as TheSaucisseFactory.Batiment;
            this.Remove(batiment);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<TheSaucisseFactory.Batiment>.ListChangedTypeDeleting)), index));
            TheSaucisseFactory.Batiment batiment = this.BaseList[index];
            if ((batiment != null))
            {
                batiment.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(batiment.Id);
            }
            if ((this._batimentsResidenceResidence != null))
            {
                batiment.Residence = null;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, batiment, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<TheSaucisseFactory.Batiment> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<TheSaucisseFactory.Batiment> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private TheSaucisseFactory.Batiment TryGetValue(System.Guid key)
        {
            TheSaucisseFactory.Batiment batiment;
            if ((this.BaseTable.TryGetValue(key, out batiment) == true))
            {
                return batiment;
            }
            return null;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                TheSaucisseFactory.Batiment batiment = this[index];
                batiment.Save();
                if ((batiment.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(batiment);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._batimentsResidenceResidence = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.Batiment batiment = new TheSaucisseFactory.Batiment();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(batiment)).ReadRecord(reader);
                    if ((this.BaseContains(batiment) == false))
                    {
                        this.BaseAdd(batiment);
                        count = (count + 1);
                    }
                    batiment.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.BatimentCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.BatimentCollection ret = new TheSaucisseFactory.BatimentCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.BatimentCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.BatimentCollection LoadAll()
        {
            TheSaucisseFactory.BatimentCollection ret = TheSaucisseFactory.BatimentCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Batiment", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = TheSaucisseFactory.BatimentCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadByResidence(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, TheSaucisseFactory.Residence residence)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState residenceState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((residence != null))
            {
                residenceState = residence.EntityState;
            }
            this._batimentsResidenceResidence = residence;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.Batiment batiment = new TheSaucisseFactory.Batiment();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(batiment)).ReadRecord(reader);
                    if ((this.BaseContains(batiment) == false))
                    {
                        this.BaseAdd(batiment);
                        count = (count + 1);
                    }
                    batiment.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((residence != null))
            {
                residence.EntityState = residenceState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.BatimentCollection PageLoadByResidence(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Residence residence)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.BatimentCollection ret = new TheSaucisseFactory.BatimentCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.BatimentCollection.PageDataLoadByResidence(pageOptions, residence);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByResidence(pageIndex, pageSize, pageOptions, reader, residence);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.BatimentCollection LoadByResidence(TheSaucisseFactory.Residence residence)
        {
            TheSaucisseFactory.BatimentCollection ret = TheSaucisseFactory.BatimentCollection.PageLoadByResidence(int.MinValue, int.MaxValue, null, residence);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByResidence(CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Residence residence)
        {
            if ((residence == null))
            {
                return null;
            }
            if ((residence.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "residence", "TheSaucisseFactory.Residence");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Batiment", "LoadByResidence");
            persistence.AddParameter("@ResidenceId", residence.Id, CodeFluentPersistence.DefaultGuidValue);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByResidence(TheSaucisseFactory.Residence residence)
        {
            System.Data.IDataReader reader = TheSaucisseFactory.BatimentCollection.PageDataLoadByResidence(null, residence);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(TheSaucisseFactory.BatimentCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(TheSaucisseFactory.Batiment)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<TheSaucisseFactory.Batiment> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((TheSaucisseFactory.Batiment)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual TheSaucisseFactory.BatimentCollection Clone(bool deep)
        {
            TheSaucisseFactory.BatimentCollection ret = new TheSaucisseFactory.BatimentCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm3483504819.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            TheSaucisseFactory.Batiment add = new TheSaucisseFactory.Batiment();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((TheSaucisseFactory.Batiment)(e.NewObject));
            if ((add == null))
            {
                add = new TheSaucisseFactory.Batiment();
            }
            add.Id = System.Guid.NewGuid();
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm3483504819.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm3483504819.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm3483504819.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm3483504819.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<TheSaucisseFactory.Batiment> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            TheSaucisseFactory.Batiment existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<System.Guid>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<System.Guid> item = ((CodeFluent.Runtime.Utilities.IKeyable<System.Guid>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.BatimentCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.BatimentCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.BatimentCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return TheSaucisseFactory.BatimentCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.BatimentCollection PageLoadByResidence(int pageIndex, int pageSize, System.Guid residenceId)
        {
            TheSaucisseFactory.Residence residence = TheSaucisseFactory.Residence.Load(residenceId);
            if ((residence == null))
            {
                return new TheSaucisseFactory.BatimentCollection();
            }
            return TheSaucisseFactory.BatimentCollection.PageLoadByResidence(pageIndex, pageSize, null, residence);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                return false;
            }
            bool ret = batiment.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(TheSaucisseFactory.Batiment batiment)
        {
            bool ret = TheSaucisseFactory.Batiment.Save(batiment);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(TheSaucisseFactory.Batiment batiment)
        {
            if ((batiment == null))
            {
                return false;
            }
            bool ret = batiment.Delete();
            return ret;
        }
    }
}
