//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSaucisseFactory
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TheSaucisseFactory.GainEnergyCoin))]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Namespace="http://schemas.thesaucissefactory.com", ItemName="GainEnergyCoin")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TheSaucisseFactory.GainEnergyCoin))]
    public partial class GainEnergyCoinCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<TheSaucisseFactory.GainEnergyCoin>, System.Collections.Generic.ICollection<TheSaucisseFactory.GainEnergyCoin>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<TheSaucisseFactory.GainEnergyCoin> _baseList = new System.Collections.Generic.List<TheSaucisseFactory.GainEnergyCoin>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.GainEnergyCoin> _baseTable = new System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.GainEnergyCoin>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private TheSaucisseFactory.Appartement _gainsEnergyCoinAppartementAppartement;
        
        [System.NonSerializedAttribute()]
        private TheSaucisseFactory.Challenge _gainsEnergyCoinChallengeChallenge;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.GainEnergyCoin> _blm481311421;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public GainEnergyCoinCollection()
        {
            this._blm481311421 = new CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.GainEnergyCoin>(this);
        }
        
        public GainEnergyCoinCollection(TheSaucisseFactory.Appartement gainsEnergyCoinAppartementAppartement, TheSaucisseFactory.Challenge gainsEnergyCoinChallengeChallenge)
        {
            this._blm481311421 = new CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.GainEnergyCoin>(this);
            this._gainsEnergyCoinAppartementAppartement = gainsEnergyCoinAppartementAppartement;
            this._gainsEnergyCoinChallengeChallenge = gainsEnergyCoinChallengeChallenge;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<TheSaucisseFactory.GainEnergyCoin> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.GainEnergyCoin> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public TheSaucisseFactory.Appartement GainsEnergyCoinAppartementAppartement
        {
            get
            {
                return this._gainsEnergyCoinAppartementAppartement;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public TheSaucisseFactory.Challenge GainsEnergyCoinChallengeChallenge
        {
            get
            {
                return this._gainsEnergyCoinChallengeChallenge;
            }
        }
        
        public TheSaucisseFactory.GainEnergyCoin this[int index]
        {
            get
            {
                return ((TheSaucisseFactory.GainEnergyCoin)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((TheSaucisseFactory.GainEnergyCoin)(value));
            }
        }
        
        public TheSaucisseFactory.GainEnergyCoin this[System.Guid id]
        {
            get
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                TheSaucisseFactory.GainEnergyCoin i = this.TryGetValue(id);
                return i;
            }
            set
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                if ((value == null))
                {
                    TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = this.TryGetValue(id);
                    if ((gainEnergyCoin != null))
                    {
                        this.Remove(gainEnergyCoin);
                    }
                    return;
                }
                TheSaucisseFactory.GainEnergyCoin existing = this.TryGetValue(value.Id);
                if ((existing != null))
                {
                    this.Remove(existing);
                }
                this.Add(value);
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm481311421.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm481311421.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm481311421.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm481311421.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm481311421.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm481311421.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm481311421.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm481311421.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(TheSaucisseFactory.GainEnergyCoin item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(gainEnergyCoin);
            return localAdd;
        }
        
        protected virtual int BaseAdd(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                throw new System.ArgumentNullException("gainEnergyCoin");
            }
            if ((gainEnergyCoin.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "gainEnergyCoin", "TheSaucisseFactory.GainEnergyCoin");
            }
            try
            {
                this.BaseTable.Add(gainEnergyCoin.Id, gainEnergyCoin);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.GainEnergyCoinCollection", gainEnergyCoin.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.GainEnergyCoinCollection", gainEnergyCoin.Id), ae);
            }
            gainEnergyCoin.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            if ((this._gainsEnergyCoinAppartementAppartement != null))
            {
                gainEnergyCoin.Appartement = this._gainsEnergyCoinAppartementAppartement;
            }
            if ((this._gainsEnergyCoinChallengeChallenge != null))
            {
                gainEnergyCoin.Challenge = this._gainsEnergyCoinChallengeChallenge;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(gainEnergyCoin);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, gainEnergyCoin, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = null;
            try
            {
                gainEnergyCoin = ((TheSaucisseFactory.GainEnergyCoin)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((gainEnergyCoin == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(gainEnergyCoin);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<TheSaucisseFactory.GainEnergyCoin>.Add(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            this.BaseAdd(gainEnergyCoin);
        }
        
        public virtual TheSaucisseFactory.GainEnergyCoin AddByEntityKey(string key)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = TheSaucisseFactory.GainEnergyCoin.LoadByEntityKey(key);
            if (((gainEnergyCoin != null) 
                        && (this.Contains(gainEnergyCoin) == false)))
            {
                this.Add(gainEnergyCoin);
            }
            return gainEnergyCoin;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<TheSaucisseFactory.GainEnergyCoin> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(TheSaucisseFactory.GainEnergyCoin[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(TheSaucisseFactory.GainEnergyCoin[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            bool localContains = this.BaseContains(gainEnergyCoin);
            return localContains;
        }
        
        protected virtual bool BaseContains(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(gainEnergyCoin.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin;
			gainEnergyCoin = value as TheSaucisseFactory.GainEnergyCoin;
            return this.Contains(gainEnergyCoin);
        }
        
        public int IndexOf(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            int localIndexOf = this.BaseIndexOf(gainEnergyCoin);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(gainEnergyCoin);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin;
			gainEnergyCoin = value as TheSaucisseFactory.GainEnergyCoin;
            return this.IndexOf(gainEnergyCoin);
        }
        
        public void Insert(int index, TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            this.BaseInsert(index, gainEnergyCoin);
        }
        
        protected virtual void BaseInsert(int index, TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                throw new System.ArgumentNullException("gainEnergyCoin");
            }
            try
            {
                this.BaseTable.Add(gainEnergyCoin.Id, gainEnergyCoin);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.GainEnergyCoinCollection", gainEnergyCoin.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.GainEnergyCoinCollection", gainEnergyCoin.Id), ae);
            }
            this.BaseList.Insert(index, gainEnergyCoin);
            if ((this._gainsEnergyCoinAppartementAppartement != null))
            {
                gainEnergyCoin.Appartement = this._gainsEnergyCoinAppartementAppartement;
            }
            if ((this._gainsEnergyCoinChallengeChallenge != null))
            {
                gainEnergyCoin.Challenge = this._gainsEnergyCoinChallengeChallenge;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, gainEnergyCoin, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin;
			gainEnergyCoin = value as TheSaucisseFactory.GainEnergyCoin;
            this.Insert(index, gainEnergyCoin);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                TheSaucisseFactory.GainEnergyCoin GainEnergyCoin = this[0];
                this.BaseRemove(GainEnergyCoin);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            return this.BaseRemove(gainEnergyCoin);
        }
        
        protected virtual bool BaseRemove(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                throw new System.ArgumentNullException("gainEnergyCoin");
            }
            int index = this.IndexOf(gainEnergyCoin);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<TheSaucisseFactory.GainEnergyCoin>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(gainEnergyCoin);
            gainEnergyCoin.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(gainEnergyCoin.Id);
            if ((this._gainsEnergyCoinAppartementAppartement != null))
            {
                gainEnergyCoin.Appartement = null;
            }
            if ((this._gainsEnergyCoinChallengeChallenge != null))
            {
                gainEnergyCoin.Challenge = null;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, gainEnergyCoin, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin;
			gainEnergyCoin = value as TheSaucisseFactory.GainEnergyCoin;
            this.Remove(gainEnergyCoin);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<TheSaucisseFactory.GainEnergyCoin>.ListChangedTypeDeleting)), index));
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = this.BaseList[index];
            if ((gainEnergyCoin != null))
            {
                gainEnergyCoin.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(gainEnergyCoin.Id);
            }
            if ((this._gainsEnergyCoinAppartementAppartement != null))
            {
                gainEnergyCoin.Appartement = null;
            }
            if ((this._gainsEnergyCoinChallengeChallenge != null))
            {
                gainEnergyCoin.Challenge = null;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, gainEnergyCoin, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<TheSaucisseFactory.GainEnergyCoin> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<TheSaucisseFactory.GainEnergyCoin> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private TheSaucisseFactory.GainEnergyCoin TryGetValue(System.Guid key)
        {
            TheSaucisseFactory.GainEnergyCoin gainEnergyCoin;
            if ((this.BaseTable.TryGetValue(key, out gainEnergyCoin) == true))
            {
                return gainEnergyCoin;
            }
            return null;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = this[index];
                gainEnergyCoin.Save();
                if ((gainEnergyCoin.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(gainEnergyCoin);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._gainsEnergyCoinAppartementAppartement = null;
            this._gainsEnergyCoinChallengeChallenge = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = new TheSaucisseFactory.GainEnergyCoin();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(gainEnergyCoin)).ReadRecord(reader);
                    if ((this.BaseContains(gainEnergyCoin) == false))
                    {
                        this.BaseAdd(gainEnergyCoin);
                        count = (count + 1);
                    }
                    gainEnergyCoin.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.GainEnergyCoinCollection ret = new TheSaucisseFactory.GainEnergyCoinCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.GainEnergyCoinCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection LoadAll()
        {
            TheSaucisseFactory.GainEnergyCoinCollection ret = TheSaucisseFactory.GainEnergyCoinCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "GainEnergyCoin", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = TheSaucisseFactory.GainEnergyCoinCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadByAppartement(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, TheSaucisseFactory.Appartement appartement)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState appartementState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((appartement != null))
            {
                appartementState = appartement.EntityState;
            }
            this._gainsEnergyCoinAppartementAppartement = appartement;
            this._gainsEnergyCoinChallengeChallenge = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = new TheSaucisseFactory.GainEnergyCoin();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(gainEnergyCoin)).ReadRecord(reader);
                    if ((this.BaseContains(gainEnergyCoin) == false))
                    {
                        this.BaseAdd(gainEnergyCoin);
                        count = (count + 1);
                    }
                    gainEnergyCoin.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((appartement != null))
            {
                appartement.EntityState = appartementState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection PageLoadByAppartement(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Appartement appartement)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.GainEnergyCoinCollection ret = new TheSaucisseFactory.GainEnergyCoinCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.GainEnergyCoinCollection.PageDataLoadByAppartement(pageOptions, appartement);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByAppartement(pageIndex, pageSize, pageOptions, reader, appartement);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection LoadByAppartement(TheSaucisseFactory.Appartement appartement)
        {
            TheSaucisseFactory.GainEnergyCoinCollection ret = TheSaucisseFactory.GainEnergyCoinCollection.PageLoadByAppartement(int.MinValue, int.MaxValue, null, appartement);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByAppartement(CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Appartement appartement)
        {
            if ((appartement == null))
            {
                return null;
            }
            if ((appartement.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "appartement", "TheSaucisseFactory.Appartement");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "GainEnergyCoin", "LoadByAppartement");
            persistence.AddParameter("@AppartementId", appartement.Id, CodeFluentPersistence.DefaultGuidValue);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByAppartement(TheSaucisseFactory.Appartement appartement)
        {
            System.Data.IDataReader reader = TheSaucisseFactory.GainEnergyCoinCollection.PageDataLoadByAppartement(null, appartement);
            return reader;
        }
        
        private void LoadByChallenge(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, TheSaucisseFactory.Challenge challenge)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState challengeState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((challenge != null))
            {
                challengeState = challenge.EntityState;
            }
            this._gainsEnergyCoinAppartementAppartement = null;
            this._gainsEnergyCoinChallengeChallenge = challenge;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.GainEnergyCoin gainEnergyCoin = new TheSaucisseFactory.GainEnergyCoin();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(gainEnergyCoin)).ReadRecord(reader);
                    if ((this.BaseContains(gainEnergyCoin) == false))
                    {
                        this.BaseAdd(gainEnergyCoin);
                        count = (count + 1);
                    }
                    gainEnergyCoin.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((challenge != null))
            {
                challenge.EntityState = challengeState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection PageLoadByChallenge(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Challenge challenge)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.GainEnergyCoinCollection ret = new TheSaucisseFactory.GainEnergyCoinCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.GainEnergyCoinCollection.PageDataLoadByChallenge(pageOptions, challenge);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByChallenge(pageIndex, pageSize, pageOptions, reader, challenge);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection LoadByChallenge(TheSaucisseFactory.Challenge challenge)
        {
            TheSaucisseFactory.GainEnergyCoinCollection ret = TheSaucisseFactory.GainEnergyCoinCollection.PageLoadByChallenge(int.MinValue, int.MaxValue, null, challenge);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByChallenge(CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Challenge challenge)
        {
            if ((challenge == null))
            {
                return null;
            }
            if ((challenge.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "challenge", "TheSaucisseFactory.Challenge");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "GainEnergyCoin", "LoadByChallenge");
            persistence.AddParameter("@ChallengeId", challenge.Id, CodeFluentPersistence.DefaultGuidValue);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByChallenge(TheSaucisseFactory.Challenge challenge)
        {
            System.Data.IDataReader reader = TheSaucisseFactory.GainEnergyCoinCollection.PageDataLoadByChallenge(null, challenge);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(TheSaucisseFactory.GainEnergyCoinCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(TheSaucisseFactory.GainEnergyCoin)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<TheSaucisseFactory.GainEnergyCoin> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((TheSaucisseFactory.GainEnergyCoin)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual TheSaucisseFactory.GainEnergyCoinCollection Clone(bool deep)
        {
            TheSaucisseFactory.GainEnergyCoinCollection ret = new TheSaucisseFactory.GainEnergyCoinCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm481311421.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            TheSaucisseFactory.GainEnergyCoin add = new TheSaucisseFactory.GainEnergyCoin();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((TheSaucisseFactory.GainEnergyCoin)(e.NewObject));
            if ((add == null))
            {
                add = new TheSaucisseFactory.GainEnergyCoin();
            }
            add.Id = System.Guid.NewGuid();
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm481311421.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm481311421.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm481311421.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm481311421.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<TheSaucisseFactory.GainEnergyCoin> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            TheSaucisseFactory.GainEnergyCoin existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<System.Guid>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<System.Guid> item = ((CodeFluent.Runtime.Utilities.IKeyable<System.Guid>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.GainEnergyCoinCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.GainEnergyCoinCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return TheSaucisseFactory.GainEnergyCoinCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection PageLoadByAppartement(int pageIndex, int pageSize, System.Guid appartementId)
        {
            TheSaucisseFactory.Appartement appartement = TheSaucisseFactory.Appartement.Load(appartementId);
            if ((appartement == null))
            {
                return new TheSaucisseFactory.GainEnergyCoinCollection();
            }
            return TheSaucisseFactory.GainEnergyCoinCollection.PageLoadByAppartement(pageIndex, pageSize, null, appartement);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.GainEnergyCoinCollection PageLoadByChallenge(int pageIndex, int pageSize, System.Guid challengeId)
        {
            TheSaucisseFactory.Challenge challenge = TheSaucisseFactory.Challenge.Load(challengeId);
            if ((challenge == null))
            {
                return new TheSaucisseFactory.GainEnergyCoinCollection();
            }
            return TheSaucisseFactory.GainEnergyCoinCollection.PageLoadByChallenge(pageIndex, pageSize, null, challenge);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                return false;
            }
            bool ret = gainEnergyCoin.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            bool ret = TheSaucisseFactory.GainEnergyCoin.Save(gainEnergyCoin);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(TheSaucisseFactory.GainEnergyCoin gainEnergyCoin)
        {
            if ((gainEnergyCoin == null))
            {
                return false;
            }
            bool ret = gainEnergyCoin.Delete();
            return ret;
        }
    }
}
