//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSaucisseFactory
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TheSaucisseFactory.Illustration))]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Namespace="http://schemas.thesaucissefactory.com", ItemName="Illustration")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TheSaucisseFactory.Illustration))]
    public partial class IllustrationCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<TheSaucisseFactory.Illustration>, System.Collections.Generic.ICollection<TheSaucisseFactory.Illustration>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<TheSaucisseFactory.Illustration> _baseList = new System.Collections.Generic.List<TheSaucisseFactory.Illustration>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.Illustration> _baseTable = new System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.Illustration>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private TheSaucisseFactory.Challenge _illustrationsChallengeChallenge;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.Illustration> _blm1629958279;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public IllustrationCollection()
        {
            this._blm1629958279 = new CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.Illustration>(this);
        }
        
        public IllustrationCollection(TheSaucisseFactory.Challenge illustrationsChallengeChallenge)
        {
            this._blm1629958279 = new CodeFluent.Runtime.Utilities.BindingListManager<TheSaucisseFactory.Illustration>(this);
            this._illustrationsChallengeChallenge = illustrationsChallengeChallenge;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<TheSaucisseFactory.Illustration> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<System.Guid, TheSaucisseFactory.Illustration> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public TheSaucisseFactory.Challenge IllustrationsChallengeChallenge
        {
            get
            {
                return this._illustrationsChallengeChallenge;
            }
        }
        
        public TheSaucisseFactory.Illustration this[int index]
        {
            get
            {
                return ((TheSaucisseFactory.Illustration)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((TheSaucisseFactory.Illustration)(value));
            }
        }
        
        public TheSaucisseFactory.Illustration this[System.Guid id]
        {
            get
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                TheSaucisseFactory.Illustration i = this.TryGetValue(id);
                return i;
            }
            set
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                if ((value == null))
                {
                    TheSaucisseFactory.Illustration illustration = this.TryGetValue(id);
                    if ((illustration != null))
                    {
                        this.Remove(illustration);
                    }
                    return;
                }
                TheSaucisseFactory.Illustration existing = this.TryGetValue(value.Id);
                if ((existing != null))
                {
                    this.Remove(existing);
                }
                this.Add(value);
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm1629958279.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm1629958279.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm1629958279.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm1629958279.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm1629958279.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm1629958279.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm1629958279.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm1629958279.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(TheSaucisseFactory.Illustration item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(TheSaucisseFactory.Illustration illustration)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(illustration);
            return localAdd;
        }
        
        protected virtual int BaseAdd(TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                throw new System.ArgumentNullException("illustration");
            }
            if ((illustration.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "illustration", "TheSaucisseFactory.Illustration");
            }
            try
            {
                this.BaseTable.Add(illustration.Id, illustration);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.IllustrationCollection", illustration.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.IllustrationCollection", illustration.Id), ae);
            }
            illustration.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            if ((this._illustrationsChallengeChallenge != null))
            {
                illustration.Challenge = this._illustrationsChallengeChallenge;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(illustration);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, illustration, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            TheSaucisseFactory.Illustration illustration = null;
            try
            {
                illustration = ((TheSaucisseFactory.Illustration)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((illustration == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(illustration);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<TheSaucisseFactory.Illustration>.Add(TheSaucisseFactory.Illustration illustration)
        {
            this.BaseAdd(illustration);
        }
        
        public virtual TheSaucisseFactory.Illustration AddByEntityKey(string key)
        {
            TheSaucisseFactory.Illustration illustration = TheSaucisseFactory.Illustration.LoadByEntityKey(key);
            if (((illustration != null) 
                        && (this.Contains(illustration) == false)))
            {
                this.Add(illustration);
            }
            return illustration;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<TheSaucisseFactory.Illustration> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(TheSaucisseFactory.Illustration[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(TheSaucisseFactory.Illustration[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(TheSaucisseFactory.Illustration illustration)
        {
            bool localContains = this.BaseContains(illustration);
            return localContains;
        }
        
        protected virtual bool BaseContains(TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(illustration.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            TheSaucisseFactory.Illustration illustration;
			illustration = value as TheSaucisseFactory.Illustration;
            return this.Contains(illustration);
        }
        
        public int IndexOf(TheSaucisseFactory.Illustration illustration)
        {
            int localIndexOf = this.BaseIndexOf(illustration);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(illustration);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            TheSaucisseFactory.Illustration illustration;
			illustration = value as TheSaucisseFactory.Illustration;
            return this.IndexOf(illustration);
        }
        
        public void Insert(int index, TheSaucisseFactory.Illustration illustration)
        {
            this.BaseInsert(index, illustration);
        }
        
        protected virtual void BaseInsert(int index, TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                throw new System.ArgumentNullException("illustration");
            }
            try
            {
                this.BaseTable.Add(illustration.Id, illustration);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.IllustrationCollection", illustration.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.IllustrationCollection", illustration.Id), ae);
            }
            this.BaseList.Insert(index, illustration);
            if ((this._illustrationsChallengeChallenge != null))
            {
                illustration.Challenge = this._illustrationsChallengeChallenge;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, illustration, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            TheSaucisseFactory.Illustration illustration;
			illustration = value as TheSaucisseFactory.Illustration;
            this.Insert(index, illustration);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                TheSaucisseFactory.Illustration Illustration = this[0];
                this.BaseRemove(Illustration);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(TheSaucisseFactory.Illustration illustration)
        {
            return this.BaseRemove(illustration);
        }
        
        protected virtual bool BaseRemove(TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                throw new System.ArgumentNullException("illustration");
            }
            int index = this.IndexOf(illustration);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<TheSaucisseFactory.Illustration>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(illustration);
            illustration.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(illustration.Id);
            if ((this._illustrationsChallengeChallenge != null))
            {
                illustration.Challenge = null;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, illustration, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            TheSaucisseFactory.Illustration illustration;
			illustration = value as TheSaucisseFactory.Illustration;
            this.Remove(illustration);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<TheSaucisseFactory.Illustration>.ListChangedTypeDeleting)), index));
            TheSaucisseFactory.Illustration illustration = this.BaseList[index];
            if ((illustration != null))
            {
                illustration.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(illustration.Id);
            }
            if ((this._illustrationsChallengeChallenge != null))
            {
                illustration.Challenge = null;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, illustration, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<TheSaucisseFactory.Illustration> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<TheSaucisseFactory.Illustration> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private TheSaucisseFactory.Illustration TryGetValue(System.Guid key)
        {
            TheSaucisseFactory.Illustration illustration;
            if ((this.BaseTable.TryGetValue(key, out illustration) == true))
            {
                return illustration;
            }
            return null;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                TheSaucisseFactory.Illustration illustration = this[index];
                illustration.Save();
                if ((illustration.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(illustration);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._illustrationsChallengeChallenge = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.Illustration illustration = new TheSaucisseFactory.Illustration();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(illustration)).ReadRecord(reader);
                    if ((this.BaseContains(illustration) == false))
                    {
                        this.BaseAdd(illustration);
                        count = (count + 1);
                    }
                    illustration.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.IllustrationCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.IllustrationCollection ret = new TheSaucisseFactory.IllustrationCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.IllustrationCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.IllustrationCollection LoadAll()
        {
            TheSaucisseFactory.IllustrationCollection ret = TheSaucisseFactory.IllustrationCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Illustration", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = TheSaucisseFactory.IllustrationCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadByChallenge(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, TheSaucisseFactory.Challenge challenge)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState challengeState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((challenge != null))
            {
                challengeState = challenge.EntityState;
            }
            this._illustrationsChallengeChallenge = challenge;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    TheSaucisseFactory.Illustration illustration = new TheSaucisseFactory.Illustration();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(illustration)).ReadRecord(reader);
                    if ((this.BaseContains(illustration) == false))
                    {
                        this.BaseAdd(illustration);
                        count = (count + 1);
                    }
                    illustration.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((challenge != null))
            {
                challenge.EntityState = challengeState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.IllustrationCollection PageLoadByChallenge(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Challenge challenge)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            TheSaucisseFactory.IllustrationCollection ret = new TheSaucisseFactory.IllustrationCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = TheSaucisseFactory.IllustrationCollection.PageDataLoadByChallenge(pageOptions, challenge);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByChallenge(pageIndex, pageSize, pageOptions, reader, challenge);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.IllustrationCollection LoadByChallenge(TheSaucisseFactory.Challenge challenge)
        {
            TheSaucisseFactory.IllustrationCollection ret = TheSaucisseFactory.IllustrationCollection.PageLoadByChallenge(int.MinValue, int.MaxValue, null, challenge);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByChallenge(CodeFluent.Runtime.PageOptions pageOptions, TheSaucisseFactory.Challenge challenge)
        {
            if ((challenge == null))
            {
                return null;
            }
            if ((challenge.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "challenge", "TheSaucisseFactory.Challenge");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Illustration", "LoadByChallenge");
            persistence.AddParameter("@ChallengeId", challenge.Id, CodeFluentPersistence.DefaultGuidValue);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TheSaucisseFactory.Constants.TheSaucisseFactoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByChallenge(TheSaucisseFactory.Challenge challenge)
        {
            System.Data.IDataReader reader = TheSaucisseFactory.IllustrationCollection.PageDataLoadByChallenge(null, challenge);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(TheSaucisseFactory.IllustrationCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(TheSaucisseFactory.Illustration)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<TheSaucisseFactory.Illustration> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((TheSaucisseFactory.Illustration)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual TheSaucisseFactory.IllustrationCollection Clone(bool deep)
        {
            TheSaucisseFactory.IllustrationCollection ret = new TheSaucisseFactory.IllustrationCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm1629958279.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            TheSaucisseFactory.Illustration add = new TheSaucisseFactory.Illustration();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((TheSaucisseFactory.Illustration)(e.NewObject));
            if ((add == null))
            {
                add = new TheSaucisseFactory.Illustration();
            }
            add.Id = System.Guid.NewGuid();
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm1629958279.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm1629958279.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm1629958279.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm1629958279.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<TheSaucisseFactory.Illustration> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            TheSaucisseFactory.Illustration existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<System.Guid>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<System.Guid> item = ((CodeFluent.Runtime.Utilities.IKeyable<System.Guid>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "TheSaucisseFactory.IllustrationCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(TheSaucisseFactory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "TheSaucisseFactory.IllustrationCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.IllustrationCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return TheSaucisseFactory.IllustrationCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static TheSaucisseFactory.IllustrationCollection PageLoadByChallenge(int pageIndex, int pageSize, System.Guid challengeId)
        {
            TheSaucisseFactory.Challenge challenge = TheSaucisseFactory.Challenge.Load(challengeId);
            if ((challenge == null))
            {
                return new TheSaucisseFactory.IllustrationCollection();
            }
            return TheSaucisseFactory.IllustrationCollection.PageLoadByChallenge(pageIndex, pageSize, null, challenge);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                return false;
            }
            bool ret = illustration.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(TheSaucisseFactory.Illustration illustration)
        {
            bool ret = TheSaucisseFactory.Illustration.Save(illustration);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(TheSaucisseFactory.Illustration illustration)
        {
            if ((illustration == null))
            {
                return false;
            }
            bool ret = illustration.Delete();
            return ret;
        }
    }
}
