//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSaucisseFactory.Services
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    public partial class CommerceService : TheSaucisseFactory.Services.ICommerceService
    {
        
        public virtual string Validate(TheSaucisseFactory.Commerce commerce, string culture)
        {
            System.Globalization.CultureInfo cultureInfo = ConvertUtilities.ToCultureInfo(culture);
            TheSaucisseFactory.Commerce commerce1 = commerce;
            if ((commerce1 == null))
            {
                return default(string);
            }
            return commerce1.Validate(cultureInfo);
        }
        
        public virtual bool Delete(TheSaucisseFactory.Commerce commerce)
        {
            TheSaucisseFactory.Commerce commerce1 = commerce;
            if ((commerce1 == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            return commerce1.Delete();
        }
        
        public virtual TheSaucisseFactory.Commerce Load(System.Guid id)
        {
            return TheSaucisseFactory.Commerce.Load(id);
        }
        
        public virtual TheSaucisseFactory.Commerce LoadById(System.Guid id)
        {
            return TheSaucisseFactory.Commerce.LoadById(id);
        }
        
        public virtual bool Save(TheSaucisseFactory.Commerce commerce)
        {
            TheSaucisseFactory.Commerce commerce1 = commerce;
            if ((commerce1 == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            return commerce1.Save();
        }
        
        public virtual bool SaveByRef(ref TheSaucisseFactory.Commerce commerce)
        {
            TheSaucisseFactory.Commerce commerce1 = commerce;
            if ((commerce1 == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            bool ret = commerce1.Save();
            commerce = commerce1;
            return ret;
        }
        
        public virtual TheSaucisseFactory.Commerce LoadByEntityKey(string key)
        {
            return TheSaucisseFactory.Commerce.LoadByEntityKey(key);
        }
        
        public virtual bool DeleteByKey(System.Guid id)
        {
            TheSaucisseFactory.Commerce commerce = TheSaucisseFactory.Commerce.Load(id);
            if ((commerce == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            return commerce.Delete();
        }
        
        public virtual void SaveAll(TheSaucisseFactory.CommerceCollection commerceCollection)
        {
            TheSaucisseFactory.CommerceCollection commerceCollection1 = commerceCollection;
            commerceCollection1.SaveAll();
        }
        
        public virtual TheSaucisseFactory.CommerceCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            return TheSaucisseFactory.CommerceCollection.PageLoadAll(pageIndex, pageSize, pageOptions);
        }
        
        public virtual TheSaucisseFactory.CommerceCollection LoadAll()
        {
            return TheSaucisseFactory.CommerceCollection.LoadAll();
        }
        
        public virtual TheSaucisseFactory.CommerceCollection PageLoadCommercesPublicitesByMedia(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, string mediaEntityKey)
        {
            if ((mediaEntityKey == null))
            {
                throw new System.ArgumentNullException("mediaEntityKey");
            }
            TheSaucisseFactory.Media media = TheSaucisseFactory.Media.LoadByEntityKey(mediaEntityKey);
            return TheSaucisseFactory.CommerceCollection.PageLoadCommercesPublicitesByMedia(pageIndex, pageSize, pageOptions, media);
        }
        
        public virtual TheSaucisseFactory.CommerceCollection LoadCommercesPublicitesByMedia(string mediaEntityKey)
        {
            if ((mediaEntityKey == null))
            {
                throw new System.ArgumentNullException("mediaEntityKey");
            }
            TheSaucisseFactory.Media media = TheSaucisseFactory.Media.LoadByEntityKey(mediaEntityKey);
            return TheSaucisseFactory.CommerceCollection.LoadCommercesPublicitesByMedia(media);
        }
    }
}
