//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSaucisseFactory.Services
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.thesaucissefactory.com")]
    public partial interface IAppartementService
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        string Validate(TheSaucisseFactory.Appartement appartement, string culture);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool Delete(TheSaucisseFactory.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.Appartement Load(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.Appartement LoadById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool Save(TheSaucisseFactory.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool SaveByRef(ref TheSaucisseFactory.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.Appartement LoadByEntityKey(string key);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool DeleteByKey(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute()]
        void SaveAll(TheSaucisseFactory.AppartementCollection appartementCollection);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.AppartementCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.AppartementCollection LoadAll();
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.AppartementCollection PageLoadByBatiment(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, string batimentEntityKey);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.AppartementCollection LoadByBatiment(string batimentEntityKey);
    }
}
