//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSaucisseFactory.Services
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.thesaucissefactory.com")]
    public partial interface IBatimentService
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        string Validate(TheSaucisseFactory.Batiment batiment, string culture);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool Delete(TheSaucisseFactory.Batiment batiment);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.Batiment Load(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.Batiment LoadById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool Save(TheSaucisseFactory.Batiment batiment);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool SaveByRef(ref TheSaucisseFactory.Batiment batiment);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.Batiment LoadByEntityKey(string key);
        
        [System.ServiceModel.OperationContractAttribute()]
        bool DeleteByKey(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute()]
        void SaveAll(TheSaucisseFactory.BatimentCollection batimentCollection);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.BatimentCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.BatimentCollection LoadAll();
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.BatimentCollection PageLoadByResidence(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, string residenceEntityKey);
        
        [System.ServiceModel.OperationContractAttribute()]
        TheSaucisseFactory.BatimentCollection LoadByResidence(string residenceEntityKey);
    }
}
