[%@ template enumerable='Producer.VisibleMethodForms' enumerableItemName="form" enumerableTargetPathFunc='Path.Combine(Path.GetDirectoryName(TargetPath), RelativePath(form)) + ".aspx.designer" + Template.FileExtension' inherits="CodeFluent.Producers.UI.BaseTemplate" %]
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace [%=Producer.WebNamespace(form)%] {
    
    
    public partial class [%=ClassName(form)%] {
       
        /// <summary>
        /// FreeForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CodeFluent.Runtime.Web.UI.WebControls.FreeFormView FreeForm;
    }
}
